# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_equipe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipe', models.CharField(max_length=42)),
                ('lien_logo', models.CharField(max_length=100)),
                ('id_groupe', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prenom', models.CharField(max_length=42)),
                ('nom', models.CharField(max_length=42)),
                ('service', models.CharField(blank=True, max_length=42, null=True)),
                ('mail', models.EmailField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id_match', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=42)),
                ('score_eq1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_eq2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_eq1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_eq1', to='app.Equipe')),
                ('id_eq2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_eq2', to='app.Equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Pari',
            fields=[
                ('id_pari', models.AutoField(primary_key=True, serialize=False)),
                ('pari_eq1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pari_eq2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
                ('id_parieur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id_phase', models.AutoField(primary_key=True, serialize=False)),
                ('nom_phase', models.CharField(max_length=42)),
                ('groupe', models.BooleanField()),
                ('point_pari', models.PositiveSmallIntegerField()),
                ('point_score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='id_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Phase'),
        ),
    ]
